In [2]:
import pandas as pd
import os
import numpy as np

In [4]:
data_path = "/home/vmagent/app/transformer4rec_recsys2022/data/data_feat"

In [5]:
train = pd.read_parquet(os.path.join(data_path, "train.parquet"))
valid = pd.read_parquet(os.path.join(data_path, "valid.parquet"))

In [8]:
data = pd.concat([train,valid])

In [9]:
data

,session_id,item_id-list,f_1-list,f_2-list,f_3-list,f_4-list,f_5-list,f_6-list,f_7-list,f_8-list,...,f_65-list,f_66-list,f_67-list,f_68-list,f_69-list,f_70-list,f_71-list,f_72-list,f_73-list,wf
0,3,"[9655, 9655, 15085]","[0, 0, 0]","[53, 53, 53]","[0, 0, 0]","[0, 0, 0]","[0, 0, 0]","[0, 0, 0]","[0, 0, 0]","[0, 0, 0]",...,"[0, 0, 0]","[0, 0, 0]","[349, 349, 349]","[393, 393, 97]","[0, 0, 0]","[0, 0, 0]","[0, 0, 0]","[0, 0, 0]","[544, 544, 544]",0.863068
1,13,"[15654, 18626]","[0, 0]","[0, 0]","[0, 793]","[618, 618]","[0, 605]","[766, 0]","[798, 394]","[0, 636]",...,"[521, 0]","[0, 0]","[0, 0]","[351, 739]","[780, 805]","[0, 0]","[0, 0]","[219, 75]","[0, 544]",0.574915
2,18,"[4026, 2507, 18316, 24911]","[461, 461, 461, 461]","[0, 0, 0, 0]","[793, 793, 793, 793]","[618, 618, 618, 618]","[605, 605, 605, 605]","[0, 0, 0, 0]","[837, 837, 837, 837]","[0, 0, 0, 0]",...,"[0, 0, 0, 0]","[0, 0, 0, 0]","[0, 0, 0, 0]","[351, 596, 14, 31]","[116, 709, 709, 709]","[0, 0, 0, 0]","[0, 0, 0, 0]","[712, 75, 75, 75]","[0, 544, 544, 0]",0.745691
3,19,"[19896, 27937, 12804, 25772, 6341, 23687, 8316...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[793, 793, 793, 889, 793, 793, 793, 793, 793, ...","[618, 618, 618, 618, 618, 618, 618, 743, 865, ...","[605, 605, 605, 605, 605, 146, 605, 605, 58, 6...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[798, 82, 777, 452, 452, 452, 82, 452, 82, 619...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",...,"[521, 521, 610, 521, 610, 521, 521, 521, 550, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[351, 351, 351, 799, 799, 351, 351, 279, 351, ...","[592, 592, 592, 592, 592, 592, 592, 592, 592, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[7, 263, 557, 7, 75, 557, 7, 655, 7, 7, 7, 655...","[544, 91, 544, 91, 544, 544, 91, 544, 91, 544,...",0.815563
4,24,"[2927, 2927, 16064, 11662, 434, 18539, 10414, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 53, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[618, 618, 618, 0, 618, 0, 0, 0, 0, 618]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[490, 490, 394, 490, 629, 0, 394, 798, 798, 394]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",...,"[521, 521, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 349, 0, 0, 0, 0]","[502, 502, 351, 351, 351, 351, 739, 373, 745, ...","[592, 592, 885, 885, 885, 0, 805, 592, 805, 885]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[655, 655, 75, 75, 75, 0, 75, 263, 371, 75]","[544, 544, 544, 0, 544, 0, 0, 0, 0, 0]",0.558405
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81615,4439680,"[20647, 21107]","[0, 0]","[0, 0]","[0, 0]","[618, 618]","[0, 0]","[0, 766]","[394, 798]","[0, 0]",...,"[0, 521]","[0, 0]","[0, 0]","[106, 351]","[805, 780]","[0, 0]","[0, 0]","[75, 263]","[544, 544]",0.833738
81616,4439823,"[17428, 3946, 3567]","[0, 0, 0]","[0, 0, 53]","[0, 0, 0]","[618, 618, 0]","[0, 0, 0]","[0, 0, 0]","[536, 536, 0]","[0, 0, 0]",...,"[521, 521, 0]","[0, 0, 776]","[0, 0, 349]","[351, 204, 441]","[805, 805, 0]","[0, 0, 0]","[0, 0, 0]","[219, 219, 0]","[544, 544, 544]",0.962987
81617,4439898,"[12508, 3237, 18969, 17588, 8414, 3237, 8414, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[310, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 793, 793, 793, 793, 793, 793, 793, 793, 79...","[0, 618, 618, 618, 618, 618, 618, 618, 618, 61...","[0, 605, 605, 605, 605, 605, 605, 605, 605, 60...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 2, 2, 2, 2, 2, 2, 2, 2, 798, 2]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",...,"[0, 521, 521, 521, 521, 521, 521, 521, 521, 52...","[886, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[349, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[596, 745, 351, 895, 745, 745, 745, 745, 745, ...","[0, 885, 885, 885, 885, 885, 885, 885, 805, 80...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 75, 75, 75, 75, 75, 75, 75, 371, 7, 75]","[544, 544, 544, 544, 544, 544, 544, 544, 544, ...",0.902780
81618,4439949,"[16806, 16439]","[0, 0]","[0, 0]","[793, 793]","[719, 618]","[605, 605]","[0, 0]","[452, 452]","[0, 0]",...,"[521, 521]","[0, 0]","[0, 0]","[351, 379]","[740, 362]","[0, 0]","[0, 0]","[883, 7]","[91, 544]",0.681484
81619,4439986,"[23502, 13914, 13403, 19310, 12373, 27733, 2915]","[0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0]","[618, 618, 618, 618, 618, 618, 618]","[0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0]","[394, 394, 394, 394, 394, 394, 394]","[0, 0, 0, 0, 0, 0, 0]",...,"[0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0]","[739, 739, 739, 744, 739, 531, 10]","[885, 885, 885, 885, 885, 885, 885]","[0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0]","[75, 75, 75, 75, 75, 75, 75]","[544, 544, 544, 544, 544, 544, 544]",0.701726

In [12]:
data["len"] = data["f_2-list"].apply(lambda x: len(x))
data["len"].min(), data["len"].max()

(2, 101)

In [ ]:
feature {
  name: "f2-list"
  value_count {
    min: 1
    max: 100
  }
  type: INT
  int_domain {
    name: "f2"
    min: 0
    max: 20
    is_categorical: true
  }
  annotation {
    tag: "categorical"
    tag: "list"
  }
}

In [11]:
cols = [f"f_{i}-list" for i in range(1,74)]

In [18]:
dict_list = []
for i in range(1,74):
    tmp_dict = {
        "name": f"f_{i}-list",
        "value_count": {"min":2, "max":101},
        "type": "INT",
        "int_domain":{
            "name":f"f_{i}",
            "min":0,
            "max":0,
            "is_categorical": True
        },
        "annotation": {
            "tag1": "categorical",
            "tag2": "list"
          }
    }
    dict_list.append(tmp_dict)

In [39]:
def get_min(x):
    min_v = np.array(x).min()
    return min_v
def get_max(x):
    max_v = np.array(x).max()
    return max_v

In [40]:
for i in range(1,74):
    data["min"]= data[f"f_{i}-list"].apply(get_min)
    data["max"]= data[f"f_{i}-list"].apply(get_max)
    min_v = data["min"].min()
    max_v = data["max"].max()
    print(i, min_v, max_v)
    dict_list[i-1]["int_domain"]["min"] = min_v
    dict_list[i-1]["int_domain"]["max"] = max_v

1 0 771
2 0 853
3 0 889
4 0 865
5 0 650
6 0 877
7 0 838
8 0 636
9 0 369
10 0 871
11 0 859
12 0 812
13 0 905
14 0 888
15 0 656
16 0 658
17 0 614
18 0 817
19 0 774
20 0 412
21 0 890
22 0 881
23 0 510
24 0 588
25 0 850
26 0 779
27 0 423
28 0 437
29 0 753
30 0 900
31 0 768
32 0 902
33 0 873
34 0 734
35 0 667
36 0 858
37 0 469
38 0 818
39 0 795
40 0 717
41 0 826
42 0 781
43 0 894
44 0 870
45 0 899
46 0 882
47 36 884
48 0 404
49 0 806
50 0 901
51 0 897
52 0 756
53 0 707
54 0 785
55 0 879
56 1 868
57 0 811
58 0 705
59 0 856
60 0 872
61 0 898
62 0 896
63 0 887
64 0 762
65 0 813
66 0 886
67 0 755
68 0 903
69 0 885
70 0 330
71 0 904
72 0 883
73 0 544

In [51]:
dict_list

[{'name': 'f_1-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_1', 'min': 0, 'max': 771, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_2-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_2', 'min': 0, 'max': 853, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_3-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_3', 'min': 0, 'max': 889, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_4-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_4', 'min': 0, 'max': 865, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_5-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_5', 'min': 0, 'max': 650, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_6-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_6', 'min': 0, 'max': 877, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_7-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_7', 'min': 0, 'max': 838, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_8-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_8', 'min': 0, 'max': 636, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_9-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_9', 'min': 0, 'max': 369, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_10-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_10', 'min': 0, 'max': 871, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_11-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_11', 'min': 0, 'max': 859, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_12-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_12', 'min': 0, 'max': 812, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_13-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_13', 'min': 0, 'max': 905, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_14-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_14', 'min': 0, 'max': 888, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_15-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_15', 'min': 0, 'max': 656, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_16-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_16', 'min': 0, 'max': 658, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_17-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_17', 'min': 0, 'max': 614, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_18-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_18', 'min': 0, 'max': 817, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_19-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_19', 'min': 0, 'max': 774, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_20-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_20', 'min': 0, 'max': 412, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_21-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_21', 'min': 0, 'max': 890, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_22-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_22', 'min': 0, 'max': 881, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_23-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_23', 'min': 0, 'max': 510, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_24-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_24', 'min': 0, 'max': 588, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_25-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_25', 'min': 0, 'max': 850, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_26-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_26', 'min': 0, 'max': 779, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_27-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_27', 'min': 0, 'max': 423, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_28-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_28', 'min': 0, 'max': 437, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_29-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_29', 'min': 0, 'max': 753, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_30-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_30', 'min': 0, 'max': 900, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_31-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_31', 'min': 0, 'max': 768, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_32-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_32', 'min': 0, 'max': 902, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_33-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_33', 'min': 0, 'max': 873, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_34-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_34', 'min': 0, 'max': 734, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_35-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_35', 'min': 0, 'max': 667, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_36-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_36', 'min': 0, 'max': 858, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_37-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_37', 'min': 0, 'max': 469, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_38-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_38', 'min': 0, 'max': 818, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_39-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_39', 'min': 0, 'max': 795, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_40-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_40', 'min': 0, 'max': 717, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_41-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_41', 'min': 0, 'max': 826, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_42-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_42', 'min': 0, 'max': 781, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_43-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_43', 'min': 0, 'max': 894, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_44-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_44', 'min': 0, 'max': 870, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_45-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_45', 'min': 0, 'max': 899, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_46-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_46', 'min': 0, 'max': 882, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_47-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_47',
   'min': 36,
   'max': 884,
   'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_48-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_48', 'min': 0, 'max': 404, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_49-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_49', 'min': 0, 'max': 806, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_50-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_50', 'min': 0, 'max': 901, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_51-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_51', 'min': 0, 'max': 897, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_52-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_52', 'min': 0, 'max': 756, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_53-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_53', 'min': 0, 'max': 707, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_54-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_54', 'min': 0, 'max': 785, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_55-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_55', 'min': 0, 'max': 879, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_56-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_56', 'min': 1, 'max': 868, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_57-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_57', 'min': 0, 'max': 811, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_58-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_58', 'min': 0, 'max': 705, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_59-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_59', 'min': 0, 'max': 856, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_60-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_60', 'min': 0, 'max': 872, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_61-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_61', 'min': 0, 'max': 898, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_62-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_62', 'min': 0, 'max': 896, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_63-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_63', 'min': 0, 'max': 887, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_64-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_64', 'min': 0, 'max': 762, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_65-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_65', 'min': 0, 'max': 813, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_66-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_66', 'min': 0, 'max': 886, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_67-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_67', 'min': 0, 'max': 755, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_68-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_68', 'min': 0, 'max': 903, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_69-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_69', 'min': 0, 'max': 885, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_70-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_70', 'min': 0, 'max': 330, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_71-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_71', 'min': 0, 'max': 904, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_72-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_72', 'min': 0, 'max': 883, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}},
 {'name': 'f_73-list',
  'value_count': {'min': 2, 'max': 101},
  'type': 'INT',
  'int_domain': {'name': 'f_73', 'min': 0, 'max': 544, 'is_categorical': True},
  'annotation': {'tag1': 'categorical', 'tag2': 'list'}}]

In [52]:
dict_list[0]

{'name': 'f_1-list',
 'value_count': {'min': 2, 'max': 101},
 'type': 'INT',
 'int_domain': {'name': 'f_1', 'min': 0, 'max': 771, 'is_categorical': True},
 'annotation': {'tag1': 'categorical', 'tag2': 'list'}}

In [54]:
def default_dump(obj):
    if isinstance(obj, (np.integer, np.floating, np.bool_)):
        return obj.item()
    elif instance(obj, np.ndarray):
        return obj.tolist()
    else:
        return obj

In [62]:
with open(os.path.join(data_path, "schema.txt"), "w") as f:
    for i in range(len(dict_list)):
        f.write("\nfeature {\n")
        f.write(json.dumps(dict_list[i],default=default_dump))